module_name: Block Payment Logos
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - payment
  - marketing
  - advertising
description_short: The block payment logos allows you to add payment logos to your product pages.
description: description.md
images:
  - image-1.png
license: AFL
